apiVersion: apps/v1
kind: Deployment
metadata:
  name: eos-registery
spec:
  selector:
    matchLabels:
      app: eos-registery
  template:
    metadata:
      labels:
        app: eos-registery
    spec:
      containers:
      - name: eos-registery-container
        image: vikrambathala/eos_registery:1.0
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8761
      imagePullSecrets:
        - name: my-dockerhub-secret