# Use the official Jenkins LTS image as the base
FROM jenkins/jenkins:lts

# Install necessary tools
USER root
RUN apt-get update && apt-get install -y \
    curl \
    unzip

# Download and install Terraform
RUN curl -o /tmp/terraform.zip https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip \
    && unzip /tmp/terraform.zip -d /usr/local/bin/ \
    && rm /tmp/terraform.zip

# Switch back to the Jenkins user
USER jenkins
