apiVersion: v1
kind: Service
metadata:
  name: rancher-loadbalancer-service
  namespace: cattle-system
  labels:
    app: rancher
    app.kubernetes.io/managed-by: Helm
    chart: rancher-2.8.3
    heritage: Helm
    release: rancher
  annotations:
    meta.helm.sh/release-name: rancher
    meta.helm.sh/release-namespace: cattle-system
spec:
  selector:
    app: rancher
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https-internal
      port: 443
      targetPort: 444
  type: LoadBalancer
  sessionAffinity: None